blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/wow-apps/yid-py#readme
    about: Check the README for usage examples
  - name: Contributing Guidelines
    url: https://github.com/wow-apps/yid-py/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to the project
  - name: Code of Conduct
    url: https://github.com/wow-apps/yid-py/blob/main/CODE_OF_CONDUCT.md
    about: Review our coding standards and best practices
  - name: License
    url: https://github.com/wow-apps/yid-py/blob/main/LICENSE
    about: MIT License
